//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shaveer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Nutrition
    {
        public int id { get; set; }
        public string Title { get; set; }
        public string Ingredients { get; set; }
        public string NutrionalContent { get; set; }
        public string NVideoLink { get; set; }
    }
}
