//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;

public partial class ShaveerEntities : DbContext
{
    public ShaveerEntities()
        : base("name=ShaveerEntities")
    {
    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }

    public DbSet<Nutrition> Nutritions { get; set; }
    public DbSet<Training> Trainings { get; set; }
    public DbSet<Transformation> Transformations { get; set; }
    public DbSet<Wellness> Wellnesses { get; set; }
}
