//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class Nutrition
{
    public int id { get; set; }
    public string Title { get; set; }
    public string Ingredients { get; set; }
    public string NutrionalContent { get; set; }
    public string NVideoLink { get; set; }
}

public partial class Training
{
    public int id { get; set; }
    public string Title { get; set; }
    public string Description { get; set; }
    public string Duration { get; set; }
    public string TVideoLink { get; set; }
}

public partial class Transformation
{
    public int id { get; set; }
    public string Name { get; set; }
    public string Message { get; set; }
    public string ImageName { get; set; }
    public string ImagePath { get; set; }
}

public partial class Wellness
{
    public int id { get; set; }
    public string Title { get; set; }
    public string Description { get; set; }
    public string Duration { get; set; }
    public string WVideoLink { get; set; }
}
